title: Joint-Seg: Treat Foveal Avascular Zone and Retinal Vessel Segmentation in OCTA Images as a Joint Task
description: Kai Hu, SHuai Jiang, Yuan Zhang, Xuanya Li, Xieping Gao
show_downloads: false
theme: jekyll-theme-cayman

#remote_theme: pages-themes/slate@v0.2.0
#plugins:
#- jekyll-remote-theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
